# Generated by Django 4.1.4 on 2022-12-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionedPago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Amazon Video', 'Amazon Video'), ('Star +', 'Star +'), ('Paramount +', 'Paramount +')], max_length=100),
        ),
    ]
