# Generated by Django 4.1.4 on 2022-12-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionedPago', '0002_alter_services_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
