# Generated by Django 4.1.4 on 2022-12-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionedPago', '0003_alter_services_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredpayments',
            name='penalty_free_amount',
            field=models.FloatField(),
        ),
    ]
